2025-08-17 14:28:20.238803+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PRODUCT" not found; SQL statement:
select p1_0.product_id,p1_0.created_at,p1_0.created_by,p1_0.description,p1_0.image_url,p1_0.name,p1_0.popularity,p1_0.price,p1_0.updated_at,p1_0.updated_by from product p1_0 [42102-232]
2025-08-17 14:30:55.622457+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PRODUCT" not found; SQL statement:
select p1_0.product_id,p1_0.created_at,p1_0.created_by,p1_0.description,p1_0.image_url,p1_0.name,p1_0.popularity,p1_0.price,p1_0.updated_at,p1_0.updated_by from product p1_0 [42102-232]
2025-08-17 14:38:13.135726+01:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "PRODUCT" not found; SQL statement:
select p1_0.product_id,p1_0.created_at,p1_0.created_by,p1_0.description,p1_0.image_url,p1_0.name,p1_0.popularity,p1_0.price,p1_0.updated_at,p1_0.updated_by from product p1_0 [42102-232]
2025-08-21 13:21:38.713412+01:00 jdbc[27]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]PRODUCTS"; expected "PREPARE"; SQL statement:
PRODUCTS [42001-232]
2025-08-21 13:22:02.710949+01:00 jdbc[30]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:144)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:368)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:488)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:752)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:731)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
